### ISSUE TITLE
For discussion: how does FIO handled dropped transactions?

### ISSUE THREAD

**Issue by lukestokes** [fioprotocol/fips#158]
Example: https://etherscan.io/tx/0x6a270a1566fa80e409fb70842d614b8eb059c25a7a8c66abb0809f315ef359ea

The FIO Request was completed and marked as received by the payee, but they don't have the crypto in their wallet. Should we evaluate how various wallets handled dropped transactions and come up with a use case to handle this? Should FIO have knowledge about finality for various blockchains and include a warning if a request isn't verified on chain and, if something like this does happen, should the status of the FIO Request be marked as failed with an option to recreate one with the same details?

**Comment by lukestokes** [comment]
Ah, I should have taken a screenshot. Seems someone picked up the original transaction after it got dropped and rebroadcast it so it just went through. Still an interesting problem to think through. I've had other situations where an ERC20 transaction failed due to a rapid change in gas fees and it running out of gas. That would create a similar situation.

**Comment by pawmmm** [comment]
We considered this during design. That's one of the reasons that status is sent_to_blockchain and not paid or executed. The record OBT includes the tx id and it's up to the wallet to validate with chain directly. We did discuss that at some later date, the chain may include more status information, but that is difficult as the tx id is encrypted.

**Comment by pawmmm** [comment]
Closing as tracked in: https://fioprotocol.atlassian.net/browse/WP-775

**Comment by lukestokes** [comment]
@pawmmm can we revisit this? I think we have to define the standard instead of leaving it up to the wallets, either through a pattern of calls supported by our SDK or directly via some other means. This is a really big problem and if you've experienced it as much as I have, I think you would agree. FIO feels completely broken when this happen and it happens far more than it should (which, IMO, is zero).
