### ISSUE TITLE
FIP-9-Domain Leasing Feature

### ISSUE THREAD

**Issue by 9racoin** [fioprotocol/fips#44]
Domain Leasing to mean a wallet domain owned by another entity that has an agreement with the wallet in question to inflate and share registration fees of it's users.

Motivation:
Domain owners view their domain as valuable assets and would prefer not to sell. Leasing feature would lead to longer participation of both the lessor and the lessee in the industry. 

Implications: 
Domain integration should be of two types.
1. Direct integration (would mean Domain is owned by the wallet) 
2. Indirect Integration (would mean Domain is leased by the wallet in question).

Domain Leasing should have registeration fees split between 2 wallets:
1. FIO foundation wallet. ($2) constant.
2. FIO wallet to which domain is assigned.

Domain Leased means price will always be higher than $2. 

At registration (in-wallet). Users pay to a smart contract address instructed to split payment in a way that:
1. $2 goes to FIO foundation wallet (konstant)
2. $balance (set by domain owners) goes to Fio wallet to which domain is assigned.

**Comment by Thet19** [comment]
Bb

**Comment by Thet19** [comment]
Hi

**Comment by Thet19** [comment]
Hello baby

**Comment by pawmmm** [comment]
Technically this can be accomplished today using a custom instance of the [Registration Site](https://github.com/fioprotocol/fio-registrations) ran by the domain owner.

The challenge we wanted to address with "Registration Origination Bounty" is that the entity which brought the user to FIO (enabled them to register a FIO Address) only shares the initial registration fee. Each subsequent renewal is going to whatever wallet the user used to renew as it's going to the [TPID](https://developers.fioprotocol.io/fio-protocol/tpid) which enabled the renewal transaction. "Registration Origination Bounty" envisioned that the TPID used on the original registration will receive 5% of all fees ever paid by that FIO Address, even if they switch wallets in the future. The wallet TPID will not be affected.

Here's the fee distribution before "Registration Origination Bounty":
* 85% BPs
* 10% TPID
* 5% Foundation
After "Registration Origination Bounty":
* 80% BPs
* 10% TPID
* 5% Wallet which facilitated the registration
* 5% Foundation

As to being able to mark-up addresses at Protocol level we contemplated that there might be a benefit in allowing domain owners to add % price increase over whatever fee was set by BPs in exchange for some benefits offered. For example may offer discounts on amazon.con for users who pay with @vip address.

**Comment by 9racoin** [comment]
I know it is possible through the registeration site. However, for most domain owners who have no technical knowledge this might create a drawback that's why we need this feature to be addressed at protocol level. Hence, the reason for this proposal.

**Comment by city88** [comment]
Yes, I think many domain owners have no technical knowledge, they indeed need those professional people to help them in this aspect. Most domain owners really want to help in promote the use of fio, and if they can get payment by domain leasing, both fio foundation and those who want to use the domain will sure can be benefited as parts of the fee collected will reward them also.  (Not just the domain owners).

**Comment by pawmmm** [comment]
Wouldn't that incentivize domain squatting? I think we would want the domain owners to provide some value to the ecosystem beyond just being first to register a domain, i.e. get users to register a FIO Address on their domain.

**Comment by 9racoin** [comment]
@pawmmm I don't think so. Every domain owner that doesn't work to keep it's domain would ultimately lose it at some point. It is the duty of every domain owner to act as an ambassador of FIO providing education to get more users registered on its domain thereby expanding the network. Even wallets who need it most feel adamant at integrating any protocol into their product. A wallet owner will have to hold series of meetings and continuous engagement on its own to get them interested (which would have cost FIO a fortune if they were to reach every company by themselves). I believe it's a combined work of personal efforts that would make the ecosystem grow faster. It's as simple as no work; no incentive.

**Comment by oluwadamola** [comment]
I am also in support of integrating commission added by domain owners at the protocol level because it is very discouraging to have to think about spending other expenses (having a registeration site) in order to get some advantage on your investment. It also won't be smooth from user experience perspective. Domain owners still have to work to earn. I think you should accept this proposal.

**Comment by pawmmm** [comment]
I think that's being addressed with:
Premium FIO Addresses. This feature will allow domain owners to programmatically increase price of FIO Addresses on their domains in order to offer premium services to those who register such address. For example, if you pay with a FIO address on the :vip domain, you will get VIP perks.

**Comment by Brad-CurrencyHub** [comment]
> Technically this can be accomplished today using a custom instance of the [Registration Site](https://github.com/fioprotocol/fio-registrations) ran by the domain owner.
> 
> The challenge we wanted to address with "Registration Origination Bounty" is that the entity which brought the user to FIO (enabled them to register a FIO Address) only shares the initial registration fee. Each subsequent renewal is going to whatever wallet the user used to renew as it's going to the [TPID](https://developers.fioprotocol.io/fio-protocol/tpid) which enabled the renewal transaction. "Registration Origination Bounty" envisioned that the TPID used on the original registration will receive 5% of all fees ever paid by that FIO Address, even if they switch wallets in the future. The wallet TPID will not be affected.
> 
> Here's the fee distribution before "Registration Origination Bounty":
> 
> * 85% BPs
> * 10% TPID
> * 5% Foundation
> 
> After "Registration Origination Bounty":
> 
> * 80% BPs
> * 10% TPID
> * 5% Wallet which facilitated the registration
> * 5% Foundation
> 
> As to being able to mark-up addresses at Protocol level we contemplated that there might be a benefit in allowing domain owners to add % price increase over whatever fee was set by BPs in exchange for some benefits offered. For example may offer discounts on amazon.con for users who pay with @Vip address.

You should not decrease the BP % to give the balance to another actor. I would reccomend that the TPID percentage be split since they are the "reseller". This is how it works in other industries. 

The amount of the TPID split coud be  variable.  The TPID % would decrease as the facilitator % increases.

**Comment by lukestokes** [comment]
> You should not decrease the BP % to give the balance to another actor.

Thanks for chiming in, Brad. One of the concerns I have is the percentage of fees going to the BPs. It could, over time, create a situation where they are entrenched. How do you feel about the overall tokenomics model in that regard? I'm open to discussing decreasing that percentage if it makes sense, but obviously that would have to be a change the BPs wholeheartedly support and that would only make sense for them if they thought it would lead to much larger adoption (i.e. more usage and more fees for them to collect over time).

**Comment by 9racoin** [comment]
@Brad-CurrencyHub I want to be believe that the proposed solution is better as it is for two reasons. 
1) A wallet owner that owns it's domain and feels under-rewarded by the set reward system (10% TPID) could still go ahead and select option 2. (Indirect Integration) and adjust it's registeration fees as deemed fit (like adding extra $1) which goes directly to it's $FIO address to which domain is mapped. 
2) The indirect Integration would in most cases be as a result of sharing agreement between lessor and lessee. Which has to be set precisely on what amount is agreed and not based on percentages as in TPID rewards

**Comment by Brad-CurrencyHub** [comment]
@lukestokes > "create a situation where they are entrenched."
Not sure what you mean by this.

**Comment by lukestokes** [comment]
> @lukestokes > "create a situation where they are entrenched."
> Not sure what you mean by this.

If too many tokens in the economic system go just to BPs and no other stake holders in the system then they can vote for themselves, change parameters, etc which benefit the BPs but potentially harm other stake holders. A healthy balance ensures BPs are well rewarded and other stake holders are also.

**Comment by Brad-CurrencyHub** [comment]
> > @lukestokes > "create a situation where they are entrenched."
> > Not sure what you mean by this.
> 
> If too many tokens in the economic system go just to BPs and no other stake holders in the system then they can vote for themselves, change parameters, etc which benefit the BPs but potentially harm other stake holders. A healthy balance ensures BPs are well rewarded and other stake holders are also.

Understood. Thanks.

**Comment by pawmmm** [comment]
See current initiatives here: https://fioprotocol.atlassian.net/wiki/spaces/WP/overview#Current-Initiatives
