### ISSUE TITLE
FIP-10 Redesign fee computations

### ISSUE THREAD

**Issue by edrotthoff** [fioprotocol/fips#65]
this issue is intended to capture comments and discussion for FIP-10

**Comment by n8d** [comment]
Looks good 👍

**Comment by pawmmm** [comment]
Removed exception for top21 BPs. FIP-10 has been accepted. Closing.

**Comment by ericbutz** [comment]
Reopening to track the the FIP through to mainnet deployment. Link to FIP: https://github.com/fioprotocol/fips/blob/master/fip-0010.md

**Comment by pawmmm** [comment]
Discussion moved to: https://fioprotocol.atlassian.net/browse/WP-112
