### ISSUE TITLE
FIP-1.a Transfer FIO Domain

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fips#85]
The domain transfer sections of FIP-1: https://github.com/fioprotocol/fips/blob/master/fip-0001.md

**Comment by ericbutz** [comment]
Delayed. Need to release FIP-12 ahead of this FIP to prevent issue with chain fork during upgrade.

**Comment by pawmmm** [comment]
Discussion moved to: https://fioprotocol.atlassian.net/browse/WP-104
