### ISSUE TITLE
FIP-2 Improvements to paging via API

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fips#86]
Tracks comments, development and deployment of FIP-2: https://github.com/fioprotocol/fips/blob/master/fip-0002.md

**Comment by ericbutz** [comment]
Delayed. Need to release FIP-12 ahead of this FIP to prevent issue with chain fork during upgrade.

**Comment by pawmmm** [comment]
Discussion moved to: https://fioprotocol.atlassian.net/browse/WP-105
