### ISSUE TITLE
FIP-3 Provide ability to cancel a request for funds

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fips#87]
Tracks comments, development and deployment of FIP-3: https://github.com/fioprotocol/fips/blob/master/fip-0003.md

**Comment by ericbutz** [comment]
Delayed. Need to release FIP-12 ahead of this FIP to prevent issue with chain fork during upgrade.

**Comment by pawmmm** [comment]
Discussion moved to: https://fioprotocol.atlassian.net/browse/WP-106
