### ISSUE TITLE
FIP-4 Provide ability to remove pub address from the FIO protocol for a user	

### ISSUE THREAD

**Issue by ericbutz** [fioprotocol/fips#88]
Tracks comments, development and deployment of FIP-4: https://github.com/fioprotocol/fips/blob/master/fip-0004.md

**Comment by ericbutz** [comment]
Delayed. Need to release FIP-12 ahead of this FIP to prevent issue with chain fork during upgrade.

**Comment by pawmmm** [comment]
Discussion moved to: https://fioprotocol.atlassian.net/browse/WP-107
